# .github/workflows/cicd.yml

# - CICD (major)
# - "runs on ubuntu" ye sare jobs k liye common hona   --- done
# - multiple connected jobs (with if successfully)   ---
# - pull prod model from RDS and create container   ---
# - push to ECR   ---
# - Run the container on EC2/ECS   ---
# - or push particular branch k particular folder me hone pr CI pipeline trigger karo   --- done

# test-2

name: cicd pipeline
on:
  push:
    branches:
      - main
    paths:
      - './src/**'
      - .github/**

runs-on: ubuntu-latest

jobs:
  download_model:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Install Utilities 
        run: |
            pip install \
              joblib==1.3.2 \
              mlflow==2.11.0 \
              PyMySQL==1.1.0 \
              boto3==1.34.51 \
              scikit_learn==1.4.1.post1

      - name: Fetch Model From Mlflow
        run: |
          python ./prod/mlflowdb.py ${{ secrets.TRACKING_URI }}

  build_docker_image:
    needs: download_model
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        echo "COPY model.joblib /app/model.joblib" >> Dockerfile 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cicdtesting:v1.0 .

    - name: Log-in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Img
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cicdtesting:v1.0
